name: Build APK

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.14.3

      - name: Restore debug keystore from GitHub Secrets
        run: |
          if [[ ! "${{ secrets.DEBUG_KEYSTORE }}" = "" ]]; then
              echo "${{ secrets.DEBUG_KEYSTORE }}" > "debug.keystore.asc"
              if [[ -s "debug.keystore.asc" ]]; then
                  echo "Restoring debug keystore from GitHub secrets"
                  gpg -d --passphrase "debug0" --batch "debug.keystore.asc" > "debug.keystore"
              fi
          fi

      - name: Build debug APK
        run: ./gradlew assembleDebug
        env:
          DEBUG_KEYSTORE: debug.keystore
          DEBUG_KEYSTORE_PASSWORD: debug0
          DEBUG_KEY_ALIAS: debug
          DEBUG_KEY_PASSWORD: debug0

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: antigravity-debug-apk
          path: build/outputs/apk/debug/*.apk
